# Generated by Django 2.0.13 on 2020-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/djangoApp/personal_portfolio/projects/static/img'),
        ),
    ]
