# Generated by Django 2.0.13 on 2020-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200620_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='djangoApp/personal_portfolio/projects/static/img/'),
        ),
    ]
