# Generated by Django 2.0.13 on 2020-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200620_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='djangoApp/personal_portfolio/projects/static/img/'),
        ),
    ]
